//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.RoomServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoomServiceReference.IHMSService")]
    public interface IHMSService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMSService/GetRooms", ReplyAction="http://tempuri.org/IHMSService/GetRoomsResponse")]
        HMS.Models.Room[] GetRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMSService/GetRooms", ReplyAction="http://tempuri.org/IHMSService/GetRoomsResponse")]
        System.Threading.Tasks.Task<HMS.Models.Room[]> GetRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMSService/CreateRoom", ReplyAction="http://tempuri.org/IHMSService/CreateRoomResponse")]
        void CreateRoom(HMS.Models.Room roomObject);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHMSService/CreateRoom", ReplyAction="http://tempuri.org/IHMSService/CreateRoomResponse")]
        System.Threading.Tasks.Task CreateRoomAsync(HMS.Models.Room roomObject);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHMSServiceChannel : HotelManagement.RoomServiceReference.IHMSService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HMSServiceClient : System.ServiceModel.ClientBase<HotelManagement.RoomServiceReference.IHMSService>, HotelManagement.RoomServiceReference.IHMSService {
        
        public HMSServiceClient() {
        }
        
        public HMSServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HMSServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMSServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HMSServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HMS.Models.Room[] GetRooms() {
            return base.Channel.GetRooms();
        }
        
        public System.Threading.Tasks.Task<HMS.Models.Room[]> GetRoomsAsync() {
            return base.Channel.GetRoomsAsync();
        }
        
        public void CreateRoom(HMS.Models.Room roomObject) {
            base.Channel.CreateRoom(roomObject);
        }
        
        public System.Threading.Tasks.Task CreateRoomAsync(HMS.Models.Room roomObject) {
            return base.Channel.CreateRoomAsync(roomObject);
        }
    }
}
